org: thr0wn
app: hedgy-cash-orders
service: hedgy-cash-orders

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-offline

functions:
  createOracle:
    handler: ./src/orders/orders.handler.create
    events:
      - http:
          path: api/rest/orders
          method: post
          cors: true